### **Overview**

Dear Learner, 

Congratulations, you have studied NumPy all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

**Author:** Avantika Podar

In [ ]:
import numpy as np

###Task 1:   

Construct a random 3x28x28 NumPy array called *original* to represent an image and then convert this into into a 1x(3x28x28) array called *flat*. This converts it into a single row of pixels. Next, convert this to a 1D array (flatten the array using flat.flatten()). Print shape of all arrays. You may use the random function to generate the array.



In [ ]:
import numpy as np
original = np.random.randint(0, 100, size=(3, 28, 28))
print(original)

[[[69 87 31 ... 62 88 94]
  [88 46 81 ...  0 18 33]
  [ 0 55 98 ... 73 48  6]
  ...
  [14 11 30 ... 13 12 10]
  [36 93 19 ... 87  8 31]
  [16 27 53 ... 25 36 33]]

 [[85 17 36 ... 37  5 61]
  [76 22 31 ... 16 95 87]
  [97 91 82 ... 21 20 11]
  ...
  [10  6 60 ... 74 47 46]
  [55 70 27 ... 27 22 41]
  [38 65 46 ...  5 23 12]]

 [[83  4 73 ... 31 88 35]
  [60 83 59 ... 22 50 74]
  [ 9 54 17 ... 82 45 38]
  ...
  [19 48 12 ... 44  9 13]
  [10 85 99 ... 66 77 95]
  [24  0 31 ... 85 93 65]]]


In [ ]:
original.shape

(3, 28, 28)

In [ ]:
flat=original.reshape(1,-1)
print(flat)
flattened=flat.flatten()
print(flattened)

[[65 39 88 ... 35 48 31]]
[65 39 88 ... 35 48 31]


### Task 2: Print out the following: 
  * dimension of the arrays.
  * memory address of the arrays (pointer).
  * shape of the arrays.
  * data types of the arrays. 




In [ ]:
print(flattened.ndim)
print(flattened.shape)
print(flattened.dtype)

1
(2352,)
int64


### Task 3: 
Construct a new array which is a negative of the *original* array, i.e, all elements are negative of those in the *original* array. Print the new array. Add the original and new arrays. Print the result. 

In [ ]:
negoriginal=np.negative(original)
print(negoriginal)

[[[-65 -39 -88 ... -60 -69 -66]
  [-50 -22 -75 ... -96 -75 -11]
  [ -9 -95 -14 ...  -4 -47 -90]
  ...
  [-12 -42 -82 ... -66 -98 -66]
  [-79   0 -85 ... -10 -64 -42]
  [-37 -73 -20 ... -66 -33  -4]]

 [[ -3 -32 -29 ... -44 -99 -15]
  [-20 -61 -98 ... -61 -71 -83]
  [-35 -21 -41 ... -35 -15 -46]
  ...
  [-82  -6  -3 ... -58 -77 -75]
  [ -8 -84 -53 ... -28 -41 -95]
  [-55 -66 -72 ... -14 -32 -51]]

 [[-14 -90 -59 ... -54 -19 -38]
  [-62 -42 -99 ... -46 -61  -1]
  [-53 -42 -60 ... -59 -25 -13]
  ...
  [-44 -19   0 ... -24 -26 -87]
  [-75 -36 -12 ... -92 -59 -19]
  [-26 -52 -11 ... -35 -48 -31]]]


###Task 4

A 3x28x28 basically means 28x28 matrices repeated three times. How would you access the first 10 elements of the 2nd row of the second 28x28 matrix? Consider the original array for this. Print the elements.

In [ ]:
original[1,0:10,1]

array([32, 61, 21, 83,  3, 26, 65, 90, 55, 52])

### Task 5 (Optional)
A 3x28x28 image means 3 channels of Red, Green, or Blue (Popularly known as RGB image). Each color channel has a height and width, which is 28X28 in this case. The entire picture can represented through this method. Print the shape of the Blue pixel matrix and its first 3 rows.

In [ ]:
from PIL import Image
blue=original[:,:100]
print(blue)


[[[69 87 31 ... 62 88 94]
  [88 46 81 ...  0 18 33]
  [ 0 55 98 ... 73 48  6]
  ...
  [14 11 30 ... 13 12 10]
  [36 93 19 ... 87  8 31]
  [16 27 53 ... 25 36 33]]

 [[85 17 36 ... 37  5 61]
  [76 22 31 ... 16 95 87]
  [97 91 82 ... 21 20 11]
  ...
  [10  6 60 ... 74 47 46]
  [55 70 27 ... 27 22 41]
  [38 65 46 ...  5 23 12]]

 [[83  4 73 ... 31 88 35]
  [60 83 59 ... 22 50 74]
  [ 9 54 17 ... 82 45 38]
  ...
  [19 48 12 ... 44  9 13]
  [10 85 99 ... 66 77 95]
  [24  0 31 ... 85 93 65]]]


### Task 6 
Create a 1 dimensional numpy array of the first 50 even numbers. Convert this to a 10x5 numpy array and print its transpose. 

In [ ]:
array=np.arange(2,51,2)
print(array)
array2=np.arange(1,51,1)
print(array2)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


###Task 7 
Consider the 10x5 array created in Task 6. Find the mean of each row and column. You may use in built functions or write your own code.

In [ ]:
arr=np.reshape(array2,(10,5))
print(arr)
row_mean = np.mean(arr, axis=1)
row1_mean = row_mean[0]
print("Mean of Row 1 is", row1_mean)
  
row2_mean = row_mean[1]
print("Mean of Row 2 is", row2_mean)
  
row3_mean = row_mean[2]
print("Mean of Row 3 is", row3_mean)
row4_mean = row_mean[3]
print("Mean of Row 4 is", row4_mean)
  
row5_mean = row_mean[4]
print("Mean of Row 5 is", row5_mean)
  
row6_mean = row_mean[5]
print("Mean of Row 6 is", row6_mean)
row7_mean = row_mean[6]
print("Mean of Row 7 is", row7_mean)
  
row8_mean = row_mean[7]
print("Mean of Row 8 is", row8_mean)
  
row9_mean = row_mean[8]
print("Mean of Row 9 is", row9_mean)
row10_mean = row_mean[9]
print("Mean of Row 10 is", row10_mean)
  
column_mean = np.mean(arr, axis=0)
  
column1_mean = column_mean[0]
print("Mean of column 1 is", column1_mean)
  
column2_mean = column_mean[1]
print("Mean of column 2 is", column2_mean)
  
column3_mean = column_mean[2]
print("Mean of column 3 is", column3_mean)

column4_mean = column_mean[3]
print("Mean of column 4 is", column4_mean)
  
column5_mean = column_mean[4]
print("Mean of column 5 is", column5_mean)
  


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
Mean of Row 1 is 3.0
Mean of Row 2 is 8.0
Mean of Row 3 is 13.0
Mean of Row 4 is 18.0
Mean of Row 5 is 23.0
Mean of Row 6 is 28.0
Mean of Row 7 is 33.0
Mean of Row 8 is 38.0
Mean of Row 9 is 43.0
Mean of Row 10 is 48.0
Mean of column 1 is 23.5
Mean of column 2 is 24.5
Mean of column 3 is 25.5
Mean of column 4 is 26.5
Mean of column 5 is 27.5


### Task 8
Can we create a 3x3 array of the first 50 even numbers? Why or why not? What are other values of m and n for which mxn dimension is allowed for 50 elements?

In [ ]:
arr3=np.reshape(array,(3,3))

ValueError: ignored

No because the array size is 25, hence it cannot reshape into 3x3 shape